version: "3.8"

services:
  nginx:
    # 拉取最新的nginx镜像
    image: nginx:latest
    # 设置端口映射
    ports:
        - "80:80"
    # always表容器运行发生错误时一直重启
    restart: always
    # 设置挂载目录
    volumes:
        - /home/client/nginx.conf:/etc/nginx/nginx.conf
        - /home/client/dist/:/home/client/dist/
    # 设置Docker编码
    environment:
        - LANG=C.UTF-8
        - LC_ALL=C.UTF-8